site_name: RISC-V ISA CI Controller
docs_dir: docs
site_author: Julio Nunes Avelar
site_description: controller module for RISC-V core CI/CD
repo_name: riscv-isa-ci-controller
repo_url: https://github.com/LSC-Unicamp/riscv-isa-ci-controller
copyright: CC BY-SA 4.0
nav:
  - Home: index.md
theme:
  name: material
  language: pt-BR
  highlightjs: true
  features:
      - toc.integrate
      - navigation.tabs
      - navigation.expand
      - navigation.instant
      - navigation.instant.progress
      - content.code.copy
      - content.code.select
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/LSC-Unicamp/riscv-isa-ci-controller

markdown_extensions:
  - attr_list
  - md_in_html
